import { ColorType, IChartApi, createChart } from 'lightweight-charts';
import { useEffect, useRef } from 'react';

// Generated by https://quicktype.io

export interface DataItem {
  time: string;
  value: number;
}

export default function LightChart(props: { data: DataItem[], minHeight?: number }) {
  const chartContainerRef = useRef(null);
  const chartRef = useRef<IChartApi|null>(null);
  

  useEffect(() => {
    if (chartContainerRef.current && props.data.length > 0) {
      // remove the chart if it already exists
      if (chartRef.current) {
        chartRef.current.remove();
        chartRef.current = null;
      }

      // create a new chart
      const chart = createChart(chartContainerRef.current, {
        width: window.innerWidth||400, 
        height: props?.minHeight || 250,
        layout: {
          background: {
              type: ColorType.Solid,
                  color: 'transparent',
              },
          textColor: '#d1d4dc',
        },
        grid: {
          vertLines: {
            visible: false,
          },
          horzLines: {
            // color: 'rgba(42, 46, 57, 0.05)',
            visible: false
          },
        },
        rightPriceScale: {
          borderVisible: false,
          visible: true,
        },
        timeScale: {
          borderVisible: false,
          fixLeftEdge: true,
          rightBarStaysOnScroll: true,
          fixRightEdge: true,
        },
        crosshair: {
          horzLine: {
            // visible: false,
            style: 4,
          },
        },
        autoSize: true,
        
      });
      // const lineSeries = chart.addLineSeries();
      // lineSeries.setData(props.data);

      const series = chart.addAreaSeries({
        topColor: 'rgba(0,144,255, 0.618)',
        bottomColor: 'rgba(0,144,255, 0.01)',
        lineColor: 'rgba(0,144,255, 1)',
        lineWidth: 3,
      });
      series.setData(props.data); 

      const now = new Date();
      chart.timeScale().setVisibleRange({
        from: new Date(`${now.getFullYear()}-${(now.getMonth()+1) < 10 ? `0${(now.getMonth() + 1)}` : now.getMonth()+1}-${now.getDate()-7}`).getTime() / 1000 as any,
        to: now.getTime() / 1000 as any,
      });
      
      // store the chart instance in the ref
      chartRef.current = chart;
    }
    // clean up the chart when the component is unmounted
    return () => {
      if (chartRef.current) {
        chartRef.current.remove();
        chartRef.current = null;
      }
    };
  }, [props.data]);

  return <div ref={chartContainerRef} />;
};

